### ISSUE TITLE
It's a bad idea to identify private decimals to a Known Token

### ISSUE THREAD

**Issue by zcqzcg** [eightyun/Smart-contract#1]
https://github.com/eightyun/Smart-contract/blob/6c7c596274a18630890637a538f75706bd474445/src/FundMe.sol#L23

As you probably know:
https://etherscan.io/token/0xdac17f958d2ee523a2206206994597c13d831ec7#readContract
The well-known token - USDT - has only 6 decimal places.

For a constant describing the amount of USDT, it doesn't make sense to use an amount like `5*1e18`.

People will get confused: does it actually means `5` USDT or `5*1e13` USDT ?

**Comment by eightyun** [comment]
Our MINIMUM_USD uses 18 decimal places to align with the unit standard common to Solidity and ERC-20, which allows the code to be more flexible with how it handles all tokens on Ethereum. If a token with 6 decimal places (such as USDT) is involved, it will be adapted through explicit conversion logic and will not affect the correctness.
